# config file for EmuTOS user manual. Per https://www.mkdocs.org/user-guide/configuration/

site_name: EmuTOS User Manual

# theme: readthedocs
theme:
        name: mkdocs
        navigation_depth: 6
        toc_depth: 6

# repo_url: https://github.com/emutos

site_description: The User Manual for EmuTOS, a free operating system for Atari ST computers, and more.

site_author: EmuTOS Documentation Team.

copyright: Copyright &copy; 2021 through the most recent change by the respective authors.

markdown_extensions:
    - toc:
        permalink: true

# from https://github.com/apenwarr/mkdocs-exclude
plugins:
  - exclude:
      glob:
        # - exclude/this/path/*
        # - "*.tmp"
        # - "*.pdf"
        # - "*.gz"
        - "#*#"                 # Emacs temporary files.
      regex:
      #   - '.*\.(tmp|bin|tar)$'
        - '#.#'               # Emacs temporary files.
      #   - '.*(?<!(md|MD))$'     # anything not an md file.
